- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: Get Memory
      ansible.builtin.shell: free | grep Mem
      register: free
    - name: set a fact
      ansible.builtin.set_fact:
        free: "{{ free.stdout | split(' ') }}"
    - name: set facts
      ansible.builtin.set_fact:
        total: "{{ FREE[1] |int }}"
        free: "{{ FREE[3] |int }}"
    - name: print free variable
      ansible.builtin.debug:
        msg: "{{free / total }}"


