- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: Get Memory
      ansible.builtin.shell: free | grep Mem | xargs
      register: free

    - name: set a fact
      ansible.builtin.set_fact:
        FREE: "{{ free.stdout | split(' ') }}"

    - name: set facts
      ansible.builtin.set_fact:
        total: "{{ FREE[1] }}"
        free: "{{ FREE[3] }}"
        used_mem: "{{ 100 - (FREE[3]|int / FREE[1]|int * 100) }}"

    - name: print free output
      ansible.builtin.debug:
        msg: "{{ used_mem }}"




