- name: print used memory
  hosts: localhost
  tasks:
    -name: Get Memory
     ansible.builtin.shell: free | grep Mem
     register: free
    - name: print free variable
      ansible.builtin.debug:
        msg: "{{free}}"


