- name: demo on parameters
  hosts: localhost
  tasks:
    - name: get a parameter from a parameter store
      ansible.builtin.debug:
        msg: "{{ lookup('aws_ssm', 'test', region='us-east-1' ) }}"